runtime: python27
api_version: 1
threadsafe: false
handlers:
- url: /admin/dist
  static_dir: admin/dist

- url: /admin/assets
  static_dir: admin/assets

- url: /admin/scripts
  static_dir: admin/scripts

- url: /admin/(.+)
  mime_type: text/html
  static_files: admin/static/\1.html
  upload: admin/static/(.+)
  
- url: /createyouraccount.html
  static_files: createaccount.html
  upload: createaccount.html


- url: /userprofile/.*
  static_files: userprofile.html
  upload: userprofile.html


- url: /cheeseprofile/.*
  static_files: cheeseprofile.html
  upload: cheeseprofile.html

- url: /cheesemakerprofile/.*
  static_files: cheesemakerprofile.html
  upload: cheesemakerprofile.html

- url: /cheeseshopprofile/.*
  static_files: cheeseshopprofile.html
  upload: cheeseshopprofile.html




- url: /.*
  script: helloworld.application
