runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /dist
  static_dir: dist

- url: /assets
  static_dir: assets

- url: /.*
  script: main.app

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
