runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /dist
  static_dir: dist

- url: /assets
  static_dir: assets

- url: /scripts
  static_dir: scripts

- url: /(.+)
  mime_type: text/html
  static_files: static/\1.html
  upload: static/(.+)
